---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: http-fs-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/kesselborn/echo
