---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: echo
      image: alpine
      command:
        - /bin/sh
      args:
        - -c
        - echo "hello"
    - name: echo2
      image: alpine
      command:
        - /bin/sh
      args:
        - -c
        - echo "hello2"
