---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: http-fs-run-21
spec:
  serviceAccount: tekton-runner
  pipelineRef:
    name: http-fs
  resources:
    - name: git-repo
      resourceRef:
        name: http-fs-git
    - name: docker-image
      resourceRef:
        name: http-fs-image
